on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./
        id: hello
        with:
          crdYaml: crontab.yaml
          javaPackageName: com.example.stable
          crdApiGroupName: com.example.stable
